#!/usr/bin/env node
/**
 * sync-slugs.mjs — regenerate the vendored slug snapshot used by validate.mjs.
 *
 * Reads the EMCP website's source-of-truth data (brand-kits.json, prompts.json,
 * templates.json) and writes a compact, content-free snapshot of just the slug
 * identifiers + the prompt-slug -> category map. The snapshot — not the website
 * repo — is what the validator checks against, so CI/pre-commit stays offline
 * and deterministic (see docs/INDUSTRY_SKILL_PACKS_PLAN.md § 8.2).
 *
 * The snapshot holds only identifiers (slugs/category names), never prompt
 * bodies, copy, or any premium content — safe to commit to the public repo.
 *
 * Usage:
 *   node tools/verticals/sync-slugs.mjs [path-to-website/src/data]
 *   EMCP_DATA_DIR="E:/.../website/src/data" node tools/verticals/sync-slugs.mjs
 *
 * Run this whenever the Brand Kits / Prompts / Templates libraries change.
 * The resulting library-slugs.json diff makes any rename/removal visible in PR.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));

// Default to the companion website's data dir; override via argv or env.
const DEFAULT_DATA_DIR = 'E:/MSR Builds/Products/EMCP/website/src/data';
const DATA_DIR = process.argv[2] || process.env.EMCP_DATA_DIR || DEFAULT_DATA_DIR;

const OUT = join(HERE, 'library-slugs.json');

function readJson(name) {
  const p = join(DATA_DIR, name);
  try {
    return JSON.parse(readFileSync(p, 'utf8'));
  } catch (err) {
    console.error(`✗ Could not read ${p}\n  ${err.message}`);
    console.error(`  Pass the website data dir as an argument or set EMCP_DATA_DIR.`);
    process.exit(2);
  }
}

const brandKitsRaw = readJson('brand-kits.json');
const promptsRaw = readJson('prompts.json');
const templatesRaw = readJson('templates.json');

// Brand kits: categories[].kits[].slug — kit slugs only (not category slugs).
const brand_kits = brandKitsRaw.categories
  .flatMap((c) => (c.kits || []).map((k) => k.slug))
  .sort();

// Prompts: categories[].slug is a category; categories[].prompts[].slug is a prompt.
// Build the prompt-slug -> category-slug map that powers cross-category detection.
const prompt_categories = promptsRaw.categories.map((c) => c.slug).sort();
const prompts = {};
for (const c of promptsRaw.categories) {
  for (const p of c.prompts || []) {
    prompts[p.slug] = c.slug;
  }
}

// Templates: categories[].templates[].slug — template slugs only.
const templates = templatesRaw.categories
  .flatMap((c) => (c.templates || []).map((t) => t.slug))
  .sort();

const snapshot = {
  _comment:
    'Generated by tools/verticals/sync-slugs.mjs. IDs only, no premium content. Do not hand-edit.',
  generated_from: DATA_DIR.replace(/\\/g, '/'),
  brand_kits,
  prompt_categories,
  prompts, // slug -> category slug
  templates,
};

writeFileSync(OUT, JSON.stringify(snapshot, null, 2) + '\n', 'utf8');

console.log(`✓ Wrote ${OUT}`);
console.log(
  `  ${brand_kits.length} brand kits · ${prompt_categories.length} prompt categories · ` +
    `${Object.keys(prompts).length} prompts · ${templates.length} templates`,
);
