/**
 * Colour tokens (JavaScript copy of tokens.css, kept in sync by a test) and the
 * foreground/background pairs components are allowed to use for informative
 * text, each checked against WCAG 2.2 AA (spec 6.4).
 */
export const COLORS = {
	primary: '#5b5fe8',
	'primary-strong': '#4347c9',
	'primary-tint': '#eef0ff',
	'primary-tint-2': '#f7f7ff',
	'primary-soft': '#c7c9fb',
	ink: '#111827',
	'ink-2': '#1f2937',
	'text-2': '#374151',
	'text-3': '#4b5563',
	muted: '#646b78',
	faint: '#9ca3af',
	bg: '#f4f5f8',
	surface: '#ffffff',
	'surface-2': '#fafbfc',
	border: '#e6e8ef',
	'border-input': '#d9dce5',
	divider: '#eef0f4',
	'divider-2': '#f1f2f6',
	track: '#e9eaf0',
	'toggle-off': '#d6d8e0',
	dark: '#16143a',
	'code-fg': '#e5e7ff',
	'hover-border': '#b9bbf7',
	'success-bg': '#ecfdf5',
	'success-fg': '#047857',
	'success-dot': '#10b981',
	'warning-bg': '#fff7ed',
	'warning-fg': '#b45309',
	'warning-dot': '#f59e0b',
	'danger-bg': '#fef2f2',
	'danger-fg': '#b91c1c',
	'danger-icon': '#dc2626',
	'danger-border': '#fecaca',
};

// [ foreground, background, minimum ratio, where it is used ]
export const CONTRAST_PAIRS = [
	[ 'ink', 'bg', 4.5, 'page headings' ],
	[ 'ink', 'surface', 4.5, 'card text' ],
	[ 'ink-2', 'surface', 4.5, 'secondary button text' ],
	[ 'text-2', 'surface', 4.5, 'secondary text' ],
	[ 'text-3', 'track', 4.5, 'segmented options' ],
	[ 'muted', 'surface', 4.5, 'descriptions, labels' ],
	[ 'muted', 'bg', 4.5, 'page descriptions' ],
	[ 'muted', 'surface-2', 4.5, 'table headers' ],
	[ 'muted', 'divider-2', 4.5, 'empty-state text on tiles' ],
	[ 'muted', 'primary-tint', 4.5, 'meta on selected cards' ],
	[ 'primary', 'surface', 4.5, 'links' ],
	[ 'primary', 'bg', 4.5, 'links on the page background' ],
	[
		'primary-strong',
		'primary-tint',
		4.5,
		'active nav, PRO tag, text on tints',
	],
	[ 'primary-strong', 'surface', 4.5, 'outline button text' ],
	[ 'surface', 'primary', 4.5, 'primary button text' ],
	[ 'surface', 'dark', 4.5, 'save bar and dark panels' ],
	[ 'code-fg', 'dark', 4.5, 'code fields' ],
	[ 'success-fg', 'success-bg', 4.5, 'success badges' ],
	[ 'success-fg', 'surface', 4.5, 'Synced, Copied' ],
	[ 'warning-fg', 'warning-bg', 4.5, 'warning badges' ],
	[ 'warning-fg', 'surface', 4.5, 'warning text' ],
	[ 'danger-fg', 'danger-bg', 4.5, 'danger notices' ],
	[ 'danger-fg', 'surface', 4.5, 'danger button text' ],
];
